### ISSUE TITLE
Version for JSON file content

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#101]
All input data should be included inside a single JSON file (conf, data, filter).

Moreover, a version tag should be added to support the discrimination of different JSON file versions.

If the files above should stay separate, each should provide a version tag.

**Comment by iimog** [comment]
As development is currently on hold with only small bug fixes and improvements from time to time no breaking changes in the json file are expected. This has to be considered and re-opened if development is picked up again.
