### ISSUE TITLE
How to add multiple genomes?

### ISSUE THREAD

**Issue by a113n** [AliTVTeam/AliTV#103]
In the demo page [https://alitvteam.github.io/AliTV/d3/AliTV.html], it seems multiple genomes are supported. But when I try to supply multiple genomes via the --query or --reference parameters, it doesn't work properly. May I know how I could generate figures like the one in demo page?

**Comment by iimog** [comment]
Hi @a113n, you are totally right, AliTV is supposed to visualize multiple whole genomes (as shown in our demo). The visualization front end fully supports multiple genomes.
In earlier versions of AliTV only pairwise comparisons were possible. The ```AliTV.pl``` in the ```bin/``` folder is still the legacy script capable of only two genomes.
We rewrote the whole script for generating the data in the required json format and are currently putting the finishing touches on it. We will update the script and the documentation as soon as it is ready (we are aiming for tomorrow).
Sorry for the inconvenience - if you need your visualization now I can assist you in preparing the data manually (similar to the steps here: https://github.com/AliTVTeam/AliTV/blob/master/t/data/dataset001/process_testdata.sh). If you can wait another day we would be happy to have you as an early tester of our brand new perl script.

**Comment by a113n** [comment]
Sounds good! I shall wait for the next release then. Thanks for the great
tool!

On Thu, Jun 16, 2016 at 8:17 PM, Markus Ankenbrand <notifications@github.com

**Comment by iimog** [comment]
I just merged the new perl script into the repo as a git submodule. To update to the latest version I suggest removing the old AliTV folder and cloning again via
```
git clone --recursive https://github.com/AliTVTeam/AliTV
```
I also updated the README to explain the usage of the new script. There are still some rough edges and only basic documentation is available. We will continue to improve the documentation, the perl script and the visualization interface.

@a113n: I encourage you to start using the perl script right now. Tell us if you encounter a bug or if you have features that you would like to see. I'll gladly assist you in case of problems.

**Comment by a113n** [comment]
That's great! Will try that soon. Should I use
AliTV_new.pl
<https://github.com/AliTVTeam/AliTV/blob/master/bin/AliTV_new.pl> ?

On Sat, Jun 18, 2016 at 6:46 AM, Markus Ankenbrand <notifications@github.com

**Comment by greatfireball** [comment]
Hey @a113n,

After recursive cloning of our repository via 
```
git clone --recursive https://github.com/AliTVTeam/AliTV
```
just enter the `AliTV-perl-interface` folder and run the script `alitv.pl` as explained in our new [documentation](https://github.com/AliTVTeam/AliTV#usage). The file is you need to use is located [here](https://github.com/AliTVTeam/AliTV-perl-interface/blob/master/bin/alitv.pl). It is not located inside the `AliTV` repository due to it is included as submodule (think GitHub should improve the submodule handling). 

Please let us know, if you need further assistance.

**Comment by iimog** [comment]
The perl part has been further improved, it is available and documented here:
https://github.com/AliTVTeam/AliTV-perl-interface
