### ISSUE TITLE
Generated SVG contains errors identified by SVG validator

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#115]
When exporting the example dataset as SVG the [W3-Validator](https://validator.w3.org/check) reports more than 600 error. Those errors contain:
- [ ] id attributes start with digits
- [ ] id contains comma
- [ ] ids are not unique (wfeuo, fitsw)
- [ ] rect elements without heigth/width
- [ ] path without d attribute

We need to recheck what is the origin of those elements.

Nevertheless, Inkscape opens the file

**Comment by iimog** [comment]
No known practical relevance.
