### ISSUE TITLE
Lastz splitting and filtering

### ISSUE THREAD

**Issue by mictadlo** [AliTVTeam/AliTV#136]
Hi,
Is it possible to run `lastz` separately i.e. could I split my assembly into many parts and align it against the reference genome (chromosome based)? Next, I would like to filter the alignment in order to create for each chromosome a file with mapped contigs to this chromosome.

Thank you in advance.

Michal

**Comment by iimog** [comment]
Hi Michal,
there is the possibility to use pre-computed alignments as input for `AliTV`. However I'm not sure whether it is possible to split and filter those alignments. Maybe @greatfireball has some idea?

**Comment by mictadlo** [comment]
Hi @iimog,
Could you please provide how to use pre-computed alignments as input for AliTV and how a lastz command should look like so its output would be accepted by AliTV?

Thank you in advance.

Michal

**Comment by iimog** [comment]
Sorry I never replied. I'm pretty sure this is no longer relevant, still... the documentation is located here:
https://github.com/AliTVTeam/AliTV-perl-interface/blob/master/doc/alitv.md#section-alignment

Import of pre-computed alignments can still be tricky (for example identifiers have illegal characters or are duplicated in different genomes). Feel free to open a new issue if you still need this and can not get it working using the docu.
