### ISSUE TITLE
Nothing in the result json file when I run the example data

### ISSUE THREAD

**Issue by cvn001** [AliTVTeam/AliTV#137]
Dear developers,

My name is Xiangchen Li. I am very interested in AliTV and eager to use it to draw my bacterial genome alignment.

However, when I follow the Readme file to run the example data in the *chloroset* directory use this command:

`cd AliTV-perl-interface
perl -Ilib bin/alitv.pl data/chloroset/*.fasta >simple.json`

 I get nothing in simple.json file. I have tried Ubuntu 14.04 with Perl 5.18 and Ubuntu 16.04 with Perl 5.22 but no effect.

I have placed output message here. Please help me to check it. 

`You are using version v1.0.3.
INFO - Wrote temporary YAML file 'autogen_B8Ge9op.yml'
INFO - Sequence names contain non-word-characters and will be replaced by unique sequence names. Failing sequence names are: 'gi|81238323|ref|NC_001879.2|'

INFO - Created temporary folder at '/tmp/0mMVKgevCv'
INFO - Starting alignment generation... (45 alignments required)
INFO - Finished 1. alignment (44 to go; 2.22 % done)
INFO - Finished 2. alignment (43 to go; 4.44 % done)
INFO - Finished 3. alignment (42 to go; 6.67 % done)
INFO - Finished 4. alignment (41 to go; 8.89 % done)
INFO - Finished 5. alignment (40 to go; 11.11 % done)
INFO - Finished 6. alignment (39 to go; 13.33 % done)
INFO - Finished 7. alignment (38 to go; 15.56 % done)
INFO - Finished 8. alignment (37 to go; 17.78 % done)
INFO - Finished 9. alignment (36 to go; 20.00 % done)
INFO - Finished 10. alignment (35 to go; 22.22 % done)
INFO - Finished 11. alignment (34 to go; 24.44 % done)
INFO - Finished 12. alignment (33 to go; 26.67 % done)
INFO - Finished 13. alignment (32 to go; 28.89 % done)
INFO - Finished 14. alignment (31 to go; 31.11 % done)
INFO - Finished 15. alignment (30 to go; 33.33 % done)
INFO - Finished 16. alignment (29 to go; 35.56 % done)
INFO - Finished 17. alignment (28 to go; 37.78 % done)
INFO - Finished 18. alignment (27 to go; 40.00 % done)
INFO - Finished 19. alignment (26 to go; 42.22 % done)
INFO - Finished 20. alignment (25 to go; 44.44 % done)
INFO - Finished 21. alignment (24 to go; 46.67 % done)
INFO - Finished 22. alignment (23 to go; 48.89 % done)
INFO - Finished 23. alignment (22 to go; 51.11 % done)
INFO - Finished 24. alignment (21 to go; 53.33 % done)
INFO - Finished 25. alignment (20 to go; 55.56 % done)
INFO - Finished 26. alignment (19 to go; 57.78 % done)
INFO - Finished 27. alignment (18 to go; 60.00 % done)
INFO - Finished 28. alignment (17 to go; 62.22 % done)
INFO - Finished 29. alignment (16 to go; 64.44 % done)
INFO - Finished 30. alignment (15 to go; 66.67 % done)
INFO - Finished 31. alignment (14 to go; 68.89 % done)
INFO - Finished 32. alignment (13 to go; 71.11 % done)
INFO - Finished 33. alignment (12 to go; 73.33 % done)
INFO - Finished 34. alignment (11 to go; 75.56 % done)
INFO - Finished 35. alignment (10 to go; 77.78 % done)
INFO - Finished 36. alignment (9 to go; 80.00 % done)
INFO - Finished 37. alignment (8 to go; 82.22 % done)
INFO - Finished 38. alignment (7 to go; 84.44 % done)
INFO - Finished 39. alignment (6 to go; 86.67 % done)
INFO - Finished 40. alignment (5 to go; 88.89 % done)
INFO - Finished 41. alignment (4 to go; 91.11 % done)
INFO - Finished 42. alignment (3 to go; 93.33 % done)
INFO - Finished 43. alignment (2 to go; 95.56 % done)
INFO - Finished 44. alignment (1 to go; 97.78 % done)
INFO - Finished 45. alignment (0 to go; 100.00 % done)
INFO - Finished alignment generation
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - MAF input file detected, but Bioperl is bugfree... Therefore, workaround for revcom issue is not activated
INFO - Deleting temporary folder
INFO - Number of bases (1013728) is longer than the maximum allowed (1000000), therefore sequences will be excluded from JSON file
INFO - Ticks will be drawn every 1000 basepair`

**Comment by iimog** [comment]
Hi Xiangchen Li,
thanks for this report. Nice that you are using `AliTV`. Your output actually looks completely fine (for new versions of `AliTV`). Apparently we left some old documentation which is misleading. I will replace this outdated part with a link to the current one. In short:
New versions of the `AliTV-perl-interface` do not produce the `json` as `STDOUT`. Therefore, your json file is empty. Instead a `.json` file is created in your working directory with your project name (a random name if you do not supply one).
Please try this command and let me know whether it works:
```
perl bin/alitv.pl --project simple data/chloroset/*.fasta
```
This should create the `simple.json` file with proper content (or complain that the file already exists :slightly_smiling_face: )

**Comment by cvn001** [comment]
@iimog Thank you for the reply. I'm glad to tell you that the new example command is fine. I finally got the demo json format file.

**Comment by iimog** [comment]
Good to hear, thanks for the feedback. Let us know if you have other issues.
