### ISSUE TITLE
How add phylogenetic tree in json file

### ISSUE THREAD

**Issue by OrsonMM** [AliTVTeam/AliTV#149]
Dear team aliTV 

Please I install and run alitv.pl and it only give me the cromosomes aligment. 
How can add the tree in my json file?

**Comment by iimog** [comment]
Hi @OrsonMM,

did you specify a tree file when you ran `alitv.pl` like described here:
https://github.com/AliTVTeam/AliTV-perl-interface/blob/master/doc/alitv.md#section-tree

If so, which format did you use? Do the names in the tree file match your genome identifiers?

An important point to note is that AliTV does not calculate a phylogenetic tree. It is only capable of showing the tree alongside the alignment if it was provided by the user.

Happy to help you debug any issues you might face.

**Comment by iimog** [comment]
I assume this issue is fixed. Feel free to re-open if it is not.
