### ISSUE TITLE
Problems with large chromosomes

### ISSUE THREAD

**Issue by RenzoTale88** [AliTVTeam/AliTV#155]
Hello,
I'm trying to run alitv using a local installation and custom json files. The files have been created and filtered through alitv.pl and alitv-filter.pl aligning 5 mammalian-size genomes chromosome by chromosome. If I try to load the smallest chromosome (<45 mb) the software works without issues. However, when I try to load larger chromosomes (50Mb and more), I get the following error:
```
TypeError: genome2svgScale is not a function2 AliTV.js:512:18
    getLinearKaryoCoords file:///PATH/TO/Software/AliTV/d3/js/AliTV.js:512
    drawLinear file:///PATH/TO/Software/AliTV/d3/js/AliTV.js:1000
    onload file:///PATH/TO/Software/AliTV/d3/AliTV.html:592
```
This regardless of adding annotations and or phylogeny tree.
Is there some setting I'm missing in the alitv configuration? Like a maximum size allowed?

Thank you in advance for your help

Andrea

**Comment by iimog** [comment]
Hi Andrea,

thanks for reporting this issue. I've not come across this one yet. I don't see a reason for this particular error to happen dependent on the genome size. By default the sequence of large chromosomes should not be stored in the `.json` files. It might still be the large number of links (but you said you used `alitv-filter.pl` as well. How large are your `.json` files?
Is it possible for you to share one of the json files so I can reproduce and debug the error?

Best,
Markus

**Comment by RenzoTale88** [comment]
Sorry, I've just realised that there was a problem in the some chromosome names in the file (for some reasons it was always naming them with the same chromosome, regardless of my script changing the instances). It's not a bug in your software. 
I apologise for the inconvenience, and thanks for the quick reply

Andrea

**Comment by iimog** [comment]
No worries, great that you were able to fix it yourself. We are happy to help when something else comes up.

Markus
