### ISSUE TITLE
Fatal - error

### ISSUE THREAD

**Issue by Tdanis** [AliTVTeam/AliTV#158]
Hello, could you help me please with this error?

FATAL - Unable to find lastz at /home1/tdanis/Software/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.

Unable to find lastz at /home1/tdanis/Software/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.

Thank you

**Comment by iimog** [comment]
This error indicates that `lastz` is not found. This is an external dependency that is not shipped with `AliTV`. You can find it here: https://github.com/lastz/lastz
`AliTV` looks for `lastz` in your `$PATH` so if you can run `lastz` on the command line, `AliTV` should also be able to locate it.

**Comment by Tdanis** [comment]
Thank you it is ok now.
