### ISSUE TITLE
Question about cores usage

### ISSUE THREAD

**Issue by Tdanis** [AliTVTeam/AliTV#159]
Hello again, can we specify the number of cores for last, because my genomes are huge and as I saw the default usage is 2 cores.

**Comment by iimog** [comment]
Hi, it is possible to provide parameters to the alignment program like this: https://github.com/AliTVTeam/AliTV-perl-interface/blob/master/doc/alitv.md#section-alignment
However, `lastz` seems not to have a parameter that enables multi-core support. You could have a look here: https://github.com/jnarayan81/parallelLastz but I have not tested that.

**Comment by Tdanis** [comment]
Thank you very much for your help
