### ISSUE TITLE
Unable to find lastz at AliTV.pm line 99.

### ISSUE THREAD

**Issue by AllisonStander** [AliTVTeam/AliTV#162]
Good day,

I am having trouble running AliTV.

When I run alitv.pl on two fasta files, I get the following:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
You are using version v1.0.6.
INFO - Wrote temporary YAML file 'test.yml'
INFO - Sequence names contain non-word-characters and will be replaced by unique sequence names. Failing sequence names are: '514776+,514184+,514064-,514704+,514064-,514782+,514788-,514782-,514064+,514704-,514064+,514184-(circular)', 'NC_003119.8'

FATAL - Unable to find lastz at /home/allison/Downloads/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.

Unable to find lastz at /home/allison/Downloads/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lastz is located at /home/allison/Downloads/lastz-distrib-1.04.03

I am unsure how to edit the AliTV.pm file, could you please assist?
line 99 is the following:     $aln_obj->run($self->_generate_seq_set());

Kind regards,
Allison

**Comment by iimog** [comment]
Hi Allison,

`alitv.pl` assumes `lastz` to be available in the `PATH`. So you can add the folder with `lastz` (temporarily) to your `PATH` by executing this command before you run your `alitv.pl` command in the same shell:

```
export PATH=$PATH:/home/allison/Downloads/lastz-distrib-1.04.03
```

this assumes that the executable file called `lastz` is in that folder. You can permanently add this `PATH` by adding this line to your `.bashrc` or you could copy `lastz` to a location that is already on your `PATH`

As far as I know there is no way to configure the location of `lastz` using the config. @greatfireball tell me if I'm wrong.

Hope that helps! Let me know if you still have problems.
Best regards,
Markus

**Comment by greatfireball** [comment]
Hey Allison,

I wrote more or less the same answer as Markus did... Therefore, I think it should work in case you run it with `lastz` being available via `PATH` variable. 

Best,
Frank

**Comment by AllisonStander** [comment]
Thank you very much for the quick response.

I did: export PATH=$PATH:/home/allison/Downloads/lastz-distrib-1.04.03/bin before running alitv.pl and it ran successfully.

**Comment by iimog** [comment]
Awesome!

**Comment by ramadatta** [comment]
Thanks. This did fix the error for me. I had to run the following command inside `/AliTV/AliTV-perl-interface` folder as mentioned here: https://github.com/AliTVTeam/AliTV-perl-interface/issues/149

```
$ cpanm --installdeps .
```

I also deleted old yaml file.
