### ISSUE TITLE
Order of link display

### ISSUE THREAD

**Issue by ambenj** [AliTVTeam/AliTV#172]
Hello! Is it possible to change the order in which the links display? I'm using AliTV to look at a region containing gene duplications and it seems that the links on top are the ones with earlier coordinates. However for my region these earlier coordinate links also have lower identity and makes it hard to see the ones with higher identity (even after playing around with filtering and opacity). Is it possible to display the links so the ones with highest identity are on top in the display order? Thanks!

**Comment by ambenj** [comment]
Thanks so much for your quick response! The checkbox to change the display order helps a lot.

**Comment by iimog** [comment]
Awesome!
