### ISSUE TITLE
Cannot add phylogenetic tree

### ISSUE THREAD

**Issue by swmuyu** [AliTVTeam/AliTV#176]
Dear team aliTV,
I run the code with the “chloroset” data and it generates json file successfully. But when I import the json file into the web page, the page is blank.

[yml_and_json_file.zip](https://github.com/AliTVTeam/AliTV/files/8688624/yml_and_json_file.zip)

**Comment by iimog** [comment]
So I had a close look, and it seems like the names in the tree don't match the names you provide for the genomes. So in the `addtree.yml` You use names like `Cistanche_phelypaea.fasta` but in the tree file, the name seems to be only `Cistanche_phelypaea`. Note that you can define `Cistanche_phelypaea` as the name and `Cistanche_phelypaea.fasta` as the `sequence_file` like this:
```yml
genomes:
  - name: Cistanche_phelypaea
    sequence_files:
      - Cistanche_phelypaea.fasta
...
```
It is essential, however, that the genome names exactly match the names in the tree file.
Another problem is, that you provide `Nicotiana_tabacum` as three different genomes (`Nicotiana_tabacumA.fasta`, `Nicotiana_tabacumB.fasta`, `Nicotiana_tabacum.fasta`) in this case all three genome variants would need to be included in the yml file.

**Comment by swmuyu** [comment]
> So I had a close look, and it seems like the names in the tree don't match the names you provide for the genomes. So in the `addtree.yml` You use names like `Cistanche_phelypaea.fasta` but in the tree file, the name seems to be only `Cistanche_phelypaea`. Note that you can define `Cistanche_phelypaea` as the name and `Cistanche_phelypaea.fasta` as the `sequence_file` like this:
> 
> ```yaml
> genomes:
>   - name: Cistanche_phelypaea
>     sequence_files:
>       - Cistanche_phelypaea.fasta
> ...
> ```
> 
> It is essential, however, that the genome names exactly match the names in the tree file. Another problem is, that you provide `Nicotiana_tabacum` as three different genomes (`Nicotiana_tabacumA.fasta`, `Nicotiana_tabacumB.fasta`, `Nicotiana_tabacum.fasta`) in this case all three genome variants would need to be included in the yml file.

Thanks for your reply. I have successfully added the phylogenetic tree according to your instructions.

**Comment by iimog** [comment]
Awesome!
