### ISSUE TITLE
Improve skipping of chromosomes with no visible linkage information in the current configurations.

### ISSUE THREAD

**Issue by sonjahohlfeld** [AliTVTeam/AliTV#36]
With the new function filterCurrentVisibleChromosomes it is possible to filter all chromosomes without visible links when you filter the minLinkIdentity or/and the maxLinkIdentity.
The problem is, when you skip chromosomes without visible links you cannot restore their coordinates, because they are no longer calculated in getLinearKaryoCoords. When you want to restore all chromosomes you have to reload the page.
But I think it is better when you can dynamically restore hidden chromosomes without reloading the page. Maybe it is possible to add the statement if chromosomes are visible or not before drawing them.

**Comment by iimog** [comment]
This should be resolved.
