### ISSUE TITLE
Central version number for Perl code

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#61]
The AliTV.pl script needs a single version number which should be consistent with the version number of the interface.

**Comment by greatfireball** [comment]
There is one version number in the whole perl interface. It can be defined in [`AliTV-perl-interface/lib/AliTV/Base/Version.pm`](https://github.com/AliTVTeam/AliTV-perl-interface/blob/master/lib/AliTV/Base/Version.pm). Current version number is v0.1.

Let us discuss, if we really need the same version numbers on GUI and perl part. I would suggest to keep them seperate, but try to release identical major numbers.

**Comment by iimog** [comment]
Agreed. If we additionally keep separate version numbers for the json format we need to have a table of operability. Which perl version produces what json version. Which js version can handle what json version.

**Comment by greatfireball** [comment]
In general, we should try to keep backward compatibility... At least in the GUI, due to one of our statements is, that one can use an AliTV website anywhere to visualize a generated JSON. Thus, one might not be able to generate old-version JSON from perl, but is able to use the GUI to view old

**Comment by greatfireball** [comment]
In general, we should try to keep backward compatibility... At least in the GUI, due to one of our statements is, that one can use an AliTV website anywhere to visualize a generated JSON. Thus, one might not be able to generate old-version JSON from perl, but is able to use the GUI to view old JSON code.

If possible we can try to allow generation of old code with the perl part as well.
