### ISSUE TITLE
BioJS

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#64]
Contact the developers of BioJS and discuss the possibility of integrating AliTV.pl into BioJS.

**Comment by iimog** [comment]
[BioJS](biojs.net) seems to be a very broad and open framework. The goal as stated on their website is:
> BioJS builds a infrastructure, guidelines and tools to avoid the reinvention of the wheel in life sciences (= "Docker for Bio web components"). Our community builds modules than can be reused by anyone. 

Contribution is well [documented](https://github.com/biojs/biojs/blob/master/CONTRIBUTING.md)
This might be the way to go for the future. Some adjustments to the code and its deployment will be necessary. But this way others can more easily get involved. The module is better discoverable and integrable.

**Comment by iimog** [comment]
Definitly the way to go for any future development. Estimated time to convert the central visualization part to a proper BioJS component: 1 week.
The html userinterface will then be separated from the core visualization library.

**Comment by iimog** [comment]
Not planned for now
