### ISSUE TITLE
Distinguish AliTV from other software packages

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#65]
We need to distinguish AliTV from other software packages dealing with the some problem (eg. Easyfig, Mauve, BRIG, etc.)

**Comment by iimog** [comment]
Sybil
http://www.ncbi.nlm.nih.gov/pubmed/22121156

**Comment by tolot27** [comment]
And maybe to GenoplotR. The linear output looks quite similar. Indeed, AliTV has a totally different structure/model. ;-)
