### ISSUE TITLE
Logo for AliTV

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#68]
Creation of a new AliTV logo

**Comment by sonjahohlfeld** [comment]
![ali2](https://cloud.githubusercontent.com/assets/11174579/9658357/08bc9474-5249-11e5-9be3-6eba579d542c.png)

**Comment by greatfireball** [comment]
Beautiful in large scale, but too complex for smaller scales...

**Comment by sonjahohlfeld** [comment]
![alilogo2](https://cloud.githubusercontent.com/assets/11174579/10446110/13f60680-717b-11e5-83d2-1ea3312b8298.png)

Design new border of aliTV logo.

**Comment by iimog** [comment]
:+1:

**Comment by greatfireball** [comment]
:+1:

**Comment by iimog** [comment]
Will we stick with that logo or are there any ideas for changes? Looking at it now I think I like the previous version more :stuck_out_tongue_closed_eyes:

**Comment by iimog** [comment]
done
