### ISSUE TITLE
Update circular layout

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#69]

**Comment by iimog** [comment]
Updated circular layout by removing intra-genome links (those distorted the image).
Link filters are fully functional.
Draw chromosomes and draw links work as intended.
Added a warning that circular layout is experimental and lacking features.
Things to do to make it fully functional and stable:
 - add tick labels
 - add chromosome labels
 - add context menu to chromosomes (hiding, moving, etc)
 - draw features on chromosomes
 - add a genome color legend

Suggestion: decrease priority to low. Not a required feature for version 1.0.0 in my opinion.

**Comment by iimog** [comment]
Check out [biocircos.js](http://bioinfo.ibp.ac.cn/biocircos/) this can possibly help in re-adding this functionality.

**Comment by iimog** [comment]
Circular layout is clearly flagged as experimental with no plans to properly implement it for now. Will be re-opened if this changes.
