### ISSUE TITLE
Evaluate mobile compatibility

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#76]

**Comment by iimog** [comment]
AliTV works on mobile versions of Firefox (both phone and tablet tested - both android). Panning and zooming of the svg works with the standard gestures. Also click events work, the navigation bar automatically adjusts and a long tab opens the context menu (normally right click). The only feature not available in the mobile version is the independent panning on zooming of genomes (associated with the mouse release event). Also the performance is not as good as on workstations - this is expected to be less of a problem as hardware keeps improving rapidly.

Overall it should be no problem to use AliTV on a mobile device for quick analyses or demonstrations.

**Comment by iimog** [comment]
Mobile compatibility moderate.
