### ISSUE TITLE
Create demo sets

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV#77]

**Comment by sonjahohlfeld** [comment]
Some examples I thought about:
* item several EHEC strains like it is described in http://www.biomedcentral.com/1471-2164/15/17
* item Assemblies (would be nice for demonstrating the new rotate feature), see the following link http://www.nature.com/nature/journal/v485/n7400/full/nature11119.html

**Comment by iimog** [comment]
Added two more demo sets (bacteria, chromosome 4)
