### ISSUE TITLE
Add single genes to the image via the interface

### ISSUE THREAD

**Issue by sonjahohlfeld** [AliTVTeam/AliTV#90]
It may be helpful to visualize a single gene or another biological feature on a chromosome. Its information gets the user for example from a GenBank-file. This means AliTV needs the probability to draw a feature according to the following values:
- start/end in bp
- corresponding sequence
- feature group 
- style (arrow or rect)

This information is inserted by the user via the interface.

**Comment by iimog** [comment]
Not planned for now
